lzc-sdk-version: "0.1"
name: DumbAssets
package: cloud.lazycat.app.dumb-assets
version: 1.0.0
description: A Stupid Simple Asset Tracker
homepage: https://github.com/DumbWareio/DumbAssets
author: DumbWareio
application:
  subdomain: dumb-assets
  background_task: true
  public_path:
    - /
  routes:
    - /=http://dumb-assets:3000/
services:
  dumb-assets:
    image: registry.lazycat.cloud/czyt/dumbwareio/dumbassets:9076c1a74207ec53
    environment:
      - NODE_ENV=production
      - DEBUG=true
      - SITE_TITLE=DumbAssets
      - BASE_URL=https://${LAZYCAT_APP_DOMAIN}
      - DUMBASSETS_PIN=1234
      - ALLOWED_ORIGINS=*
      - APPRISE_URL=
    binds:
      - /lzcapp/var/data:/app/data
